export const OBETER_PROJETOS = 'OBETER_PROJETOS'
export const CADASTRAR_PROJETOS = 'CADASTRAR_PROJETOS'
export const EDITAR_PROJETOS = 'EDITAR_PROJETOS'
export const REMOVER_PROJETOS = 'REMOVER_PROJETOS'

export const OBETER_TAREFAS = 'OBETER_TAREFAS'
export const CADASTRAR_TAREFA = 'CADASTRAR_TAREFA'
export const EDITAR_TAREFA = 'EDITAR_TAREFA'
export const REMOVER_TAREFA = 'REMOVER_TAREFA'
